### ISSUE TITLE
bazelisk support

### ISSUE THREAD

**Issue by curtismuntz** [ngalaiko/bazel-action#19]
A lot of repositories are using [bazelisk](https://github.com/bazelbuild/bazelisk)(an official bazelbuild project) to trivially change between bazel versions.  It is instrumented off of a `.bazelversion` file in the workspace root. It'd be useful to have an action that keys off of this existing tool. 

This would allow something like the following to support literally any previous/upcoming release of bazel, along with all of the amazing features provided by bazelisk:
```
uses: ngalaiko/bazel-action/bazelisk_1.1.0@master
```

I can make a PR that implements it very trivially, but figured I'd ask your thoughts on supporting this here. If this goes beyond the scope of this project, I can make a spin-off action called `bazelisk-action` as well.

Thanks!

**Comment by ngalaiko** [comment]
Hi! 

Isn't bazelisk made to work with multiple workspaces that use different bazel versions __locally__? 

For a given workspace you always know the version of bazel, so you can always use it in the actions file.

Why would you use bazelisk in CI?

**Comment by zegl** [comment]
> Why would you use bazelisk in CI?

bazelisk has some cool features such as `--strict` and `--migrate` which can be useful to use on CI to make sure that your Bazel setup is up-to-date.

**Comment by ngalaiko** [comment]
> bazelisk has some cool features such as --strict and --migrate which can be useful to use on CI to make sure that your Bazel setup is up-to-date.

I am not sure that's the same use case as building / testing code with a known bazel version. 

@curtismuntz what's your use-case for bazelisk in ci?

**Comment by ngalaiko** [comment]
Thank you for your input! I thought a bit about this, and I no longer see any reason for this action, see https://github.com/ngalaiko/bazel-action/pull/25
